cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/mnt/home/niprabhu/ntu-dsi-dcn/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Tools/c_config.py", line 435, in run_c_code\n    bld.compile()\n  File "/mnt/home/niprabhu/ntu-dsi-dcn/.waf-1.6.7-0a94702c61504c487a251b8d0a04ca9a/waflib/Build.py", line 193, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task failed (exit status 1): \n\t{task 20438160: cxxprogram test.cpp.1.o -> testprog}\n[\'/usr/bin/g++\', \'test.cpp.1.o\', \'-o\', \'/mnt/home/niprabhu/ntu-dsi-dcn/build/.conf_check_a0f64fe4f113d65784f0c08d2434c769/testbuild/testprog\', \'-Wl,-Bstatic\', \'-Wl,-Bdynamic\', \'-L/usr/lib64\', \'-lpython2.6\']\n'
